### ISSUE TITLE
Column sizes for New-MDTable

### ISSUE THREAD

**Issue by maxim-lobanov** [Sarafian/MarkdownPS#24]
Hello!

We use this great PowerShell module to auto-generate markdown file and commit it to the repository.
But we have faced with issue that column size depend on content of the column. So if the length of one line was changes, all other lines will be realigned too and it will cause noise for the whole table. So table diff will be overcrowded

It would be great to have a parameter like `columnsSizes` - array of int, where we can hardcode width of columns and they will be used for table

I can contribute with this changes, just want to make sure that this request sounds good to you.

**Comment by Sarafian** [comment]
Hi,
I've just realized this issue is open. My apologies for the late response. I'm very happy for your kind words.

Regarding your request, there was recently a pull request GH-20 where someone else asked for alignment in the rendering and after discussions, we made changes that allow 
- per column sizing which fixes I think what you describe as a problem. In the GH-20 I've considered it a bug.
- least space used by using the `-Shrink` parameter

Both are available on the latest release [1.9](https://github.com/Sarafian/MarkdownPS/releases/tag/v1.9) and on the gallery [MarkdownPS](https://www.powershellgallery.com/packages/MarkdownPS/1.9)

Let me know if this is what you have in mind. I not, please provide some raw markdown examples like on the GH-20 to help the discussion.

**Comment by Sarafian** [comment]
I'm going to close this due to lack of feedback. As mentioned, I think this is already implemented.
